// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwxoh5f6AJR6n2nxch_mnScw48Vb1lCdE',
    appId: '1:542209828372:web:35863cdccb05736e782901',
    messagingSenderId: '542209828372',
    projectId: 'reddit-clone-113cb',
    authDomain: 'reddit-clone-113cb.firebaseapp.com',
    storageBucket: 'reddit-clone-113cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfLNC_dezgnFXboYWtDwAQOqtvBitAz7U',
    appId: '1:542209828372:android:348d2bc4cb81f6e7782901',
    messagingSenderId: '542209828372',
    projectId: 'reddit-clone-113cb',
    storageBucket: 'reddit-clone-113cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjbYlU6KmLnB6RwAxfhNHHcVcSck3wMZk',
    appId: '1:542209828372:ios:85e4b82d5878043c782901',
    messagingSenderId: '542209828372',
    projectId: 'reddit-clone-113cb',
    storageBucket: 'reddit-clone-113cb.appspot.com',
    iosBundleId: 'com.example.redditApp',
  );
}
